### ISSUE TITLE
수정할부분

### ISSUE THREAD

**Issue by Taehyeong-Lee** [java-chip-frappuccino/JavaBean_Total#2]
미수령 주문내역 정렬 asc로 변경

주석 내포 -> 외연 변경

**Comment by INHAHUMAN** [comment]
관리자 -> 주문조회 -> "주문 승인" 버튼 "수령 확인"으로 바꿀 필요 有

**Comment by devbjun** [comment]
> 관리자 -> 주문조회 -> "주문 승인" 버튼 "수령 확인"으로 바꿀 필요 有

해결 완료

**Comment by devbjun** [comment]
> 미수령 주문내역 정렬 asc로 변경
> 
> 주석 내포 -> 외연 변경

해결 완료
